[package]
name = "orb_api"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15"
serde = { version = "1", features = ["derive"] }
thiserror = "2"
uuid = { version = "1", features = ["serde"] }
actix-cors = "0.7.1"
actix-web = "4.13.0"
actix-web-grants = "4.1.2"
actix-web-httpauth = "0.8.2"
bcrypt = "0.19.0"
jsonwebtoken = { version = "10.3.0", default-features = false, features = ["rust_crypto"] }
serde_json = "1.0.149"
rust_decimal = { version = "1", features = ["serde-with-float"] }
sqlx = { version = "0.8.6", features = [
    "runtime-async-std",
    "postgres",
    "macros",
    "migrate",
    "uuid",
    "time",
    "rust_decimal",
] }
time = { version = "0.3.47", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
tracing-actix-web = "0.7"
